### ISSUE TITLE
Lose cursor position when deleting some character at the middle of string

### ISSUE THREAD

**Issue by CavalcanteLeo** [Columbina/MaskedFormatter#2]
On textfields, if you go to the middle of the text, and delete a word, it goes back to the end of the string

**Comment by Edudjr** [comment]
Hi @CavalcanteLeo! This is actually related to how you connect `MaskedFormatter` with your text field component. The formatter itself works isolated from text fields, so there is nothing I can do to solve your specific problem in this library. What you could try is using the formatter inside `shouldChangeCharactersInRange`, and feed it with the current text + new text, then either return true if the new text matches, or false if it doesnt.
Sorry I can't provide a better example or solution at the moment, but feel free to reach back with the solution, I'd be happy to include in the README. I'm closing this issue as it's not related to the formatter itself.
